# Generated by Django 4.2.9 on 2024-02-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='author',
        ),
    ]
