# Generated by Django 4.2.9 on 2024-02-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_expense_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
    ]
