# Generated by Django 4.2.9 on 2024-02-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_project_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='cost',
        ),
    ]
