# Generated by Django 4.2.9 on 2024-02-15 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_project_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-cost',)},
        ),
    ]
